const PARSE_APP_ID = process.env.PARSE_APP_ID;
const PARSE_JAVASCRIPT_KEY = process.env.PARSE_JAVASCRIPT_KEY;
const MASTER_KEY = process.env.MASTER_KEY;


module.exports = {
  PARSE_APP_ID: "Ej0RDUPRyfVU9ZLoLZt5u0iFrECWLMWYLNTVRsyY",
  PARSE_JAVASCRIPT_KEY: "ralg9W6ovhyopYcK7jDGwDAAAEYIIgSABBKhrTAG",
  MASTER_KEY: "CsP2sKJIxs2NKYv9WvBOSBM3fmbYQndFQZa6hVhc",
};
